Features/announcement
viktorgullmark/exilence-next pull request #612
Opened 2020-10-28 18:22 UTC by petterannerwall

2020-10-28 20:54 UTC, viktorgullmark requested changes

2020-10-28 20:54 UTC, viktorgullmark commented on ExilenceNextBackend/API/Controllers/StatusController.cs
> +        public async Task<IActionResult> Announcement(AnouncementModel announcement)
We need [FromBody] here, right?

2020-10-28 20:54 UTC, viktorgullmark commented on ExilenceNextBackend/API/Controllers/StatusController.cs
> +            if (announcement.Password != _configuration.GetSection("Settings")["InstanceName"])
"InstanceName" -> "AnnouncementPassword"

2020-10-28 21:33 UTC, petterannerwall commented on ExilenceNextBackend/API/Controllers/StatusController.cs
> +        public async Task<IActionResult> Announcement(AnouncementModel announcement)
Nope, it works for me using postman

2020-10-28 21:34 UTC, petterannerwall commented on ExilenceNextBackend/API/Controllers/StatusController.cs
> +            if (announcement.Password != _configuration.GetSection("Settings")["InstanceName"])
Whoops, done

2020-10-29 09:08 UTC, viktorgullmark approved these changes

2020-10-29 09:08 UTC, merged